CW2-25 Create "Contact-Us" page
csesoc/csesoc-website-2023 pull request #13
Opened 2024-06-06 16:14 UTC by QuadAces

### Why the changes are required?
- To create a contact us page
### Changes
- added a /contact-us page route
- added a contact us page that corresponds with the /contact us route
- added a 'contact us' header to the navbar
### Screenshots
<img width="1512" alt="Screenshot 2024-06-07 at 2 11 34 am" src="https://github.com/csesoc/csesoc-website-2023/assets/107918856/c99643fa-47c3-4422-ade7-5f2b6235c377">
<img width="754" alt="Screenshot 2024-06-07 at 2 12 06 am" src="https://github.com/csesoc/csesoc-website-2023/assets/107918856/bf574089-2aab-43b1-aa7e-aad525b64743">
<img width="1512" alt="Screenshot 2024-06-07 at 2 12 22 am" src="https://github.com/csesoc/csesoc-website-2023/assets/107918856/237037e6-3e34-45ec-a496-0bdf083829e4">
<img width="1510" alt="Screenshot 2024-06-07 at 2 12 34 am" src="https://github.com/csesoc/csesoc-website-2023/assets/107918856/26c33f5b-b281-4355-b934-680499d2ca63">
### Comments
- Some of the text is a bit small for my liking (looking for feedback on this)
- I also think the formatting could do some work (note that I have cloned the format of https://media.csesoc.org.au/contact-us/ as per the ticket request)
- I think this can always be made prettier, its a matter of how - I've mainly just tried keeping the CSE formatting/style consistent across pages here as an initial attempt

2024-06-13 07:03 UTC, derekxu04 commented on frontend/package.json
i dont think we need these changes?

2024-06-13 07:18 UTC, derekxu04 requested changes
Nice work to get started. Just a few cosmetic changes that might be good:

- you can remove the image Contact Us image I think, and just replace it with a Contact Us title (similar to some of the other pages)
- Would also be good to have an `iframe` embed at the bottom like in the media page, I know its outdated but we will update later
- I agree the text is probably too small, probably match the size on the media website, i think currenlty the first line of text under the image is smaller than the rest of it?
- Also get rid of the "Contact" in the text

2024-06-13 07:18 UTC, derekxu04 commented on frontend/package.json
Do we need this change? (same with package-lock.json)

2024-06-13 07:18 UTC, derekxu04 commented on frontend/src/components/Navbar.tsx
> +            <div>{'//'} Contact Us</div>
should be lower case to fit with other stuff

2024-06-13 07:18 UTC, derekxu04 commented on frontend/src/pages/contact-us.tsx
> +import Hamburger from '@/components/Hamburger';
maybe just delete this

2024-06-13 07:18 UTC, derekxu04 commented on frontend/tsconfig.json
Don't need to include this file in this pr

2024-06-13 07:18 UTC, derekxu04 commented on frontend/src/components/Hamburger.tsx
> +                <Link href={'./contact-us'}>Contact Us</Link>
Make it `href={'./contact'}` (similar to how it is called about-us but the url is just about) - will need to rename `contact-us.tsx`. Just so that the header text looks nicer

2024-06-13 07:18 UTC, derekxu04 commented on frontend/src/components/Navbar.tsx
> +            <div>{'//'} Contact Us</div>
also should be `05` instead of `04`

2024-06-13 07:25 UTC, derekxu04 commented on frontend/tsconfig.json
actually I think i'm getting this as well, we can include it actually

2024-06-16 07:50 UTC, derekxu04 requested changes
Looking better, but still some small changes.

Look above at some of the comments I've left on specific lines for some small changes that are needed.

- I think make the embed smaller (in width, right now the embed is much wider than the actual form itself).
- Make sure there is some gap between the social media and the footer

Other than that, there are some more cosmetic changes we can make but can make it later ig

2024-06-26 15:36 UTC, QuadAces commented on frontend/src/pages/contact-us.tsx
> +import Hamburger from '@/components/Hamburger';
I'm going to leave footer because its used in the page, ill remove hamburger though

2024-06-26 15:37 UTC, QuadAces commented on frontend/src/components/Hamburger.tsx
> +                <Link href={'./contact-us'}>Contact Us</Link>
done :)

2024-06-26 15:38 UTC, QuadAces commented on frontend/src/components/Navbar.tsx
> +            <div>{'//'} Contact Us</div>
done :)

2024-06-26 15:43 UTC, QuadAces commented
I've made the iframe smaller. I'm not sure how you'd like it alligned. It's alligned left to match with being under the text since fundamentally its a bit awkward to center. I've done everything else (relatively hastily but I believe I've covered everything). Let me know if theres anything else :)

2024-06-27 07:44 UTC, derekxu04 commented
Merging this into the `CW2-26-Add-relevant-content-for-each-section` branch

2024-06-27 07:44 UTC, closed without merging