CW2 28 create modal on sponsor click
csesoc/csesoc-website-2023 pull request #16
Opened 2024-06-20 10:48 UTC by QuadAces

### Why the changes are required?
Because we want a modal to show up when we click on a sponsor!
### Changes
- added a setstate to keep track of a modal
- added a setstate to keep track of modal information (yes I could use useReducer or I could just not)
- changed sponsor TS interface to have a description
- added modal component
### Screenshots
![Screenshot 2024-06-20 at 8 47 43 pm](https://github.com/csesoc/csesoc-website-2023/assets/107918856/b5c635dc-98fd-4465-8ce9-deea462b817c)
![Screenshot 2024-06-20 at 8 47 54 pm](https://github.com/csesoc/csesoc-website-2023/assets/107918856/2c9145d6-3a72-4c57-9f30-02880fbd9588)
![Screenshot 2024-06-20 at 8 48 07 pm](https://github.com/csesoc/csesoc-website-2023/assets/107918856/ff757ecc-32f5-47c5-9cc1-b0b1fba72834)
### Comments
May I say that the datastructure to keep track of our sponsors is awful. Since we have objects for each sponsor level (const diamond = {} and also have const gold = {}) I think this is really hard to work with as I had to manipulate each of the components mapped to show a modal separately. I also suggest adding a name to the sponsors datastructure field also.

Lastly, there are some errors with the source for some of the company logos and svgs. I understand Ming is working on this, just note that some svgs/images dont show on click for the modal.

2024-06-23 11:41 UTC, derekxu04 requested changes
Nice work, looks really good!

Just some changes:
- I've noted some changes above on specific lines
- Would be nice to either indicate that the logo is clickable in the modal, or to just have a "Learn more" button / text or something, otherwise it is not super obvious 

Comments:
- Do you know why some of the svgs don't show up?
- With regards to the format of `data.ts`, I don't see any way of avoiding having to split the sponsors into the three sections. If we want to avoid repeating the code to do with the modal, we can make it even more modular and make a `SponsorSection` component or something for each level, which would work I think, or maybe just write a function that does that for you without needing to make it its own entire new component
- Agree with adding the `name` property to each company, either you can do that or I'll can do that at some point

2024-06-23 11:41 UTC, derekxu04 commented on frontend/src/components/Sponsors/sponsorModal.tsx
> +import { MouseEventHandler } from 'react';
Can delete this line

2024-06-23 11:41 UTC, derekxu04 commented on frontend/src/components/Sponsors/sponsorModal.tsx
> +export default function SponsorModal(props: { sponsorInfo: sponsorInfo | null; setFalse: any }) {
Can make the type of setFalse to be a function (something like `() => void` or something)

2024-06-23 11:41 UTC, derekxu04 commented on frontend/src/components/Sponsors/sponsorModal.tsx
> +          <img src={`./${props.sponsorInfo.svg}`} alt={props.sponsorInfo.alt} />
Can we specify a width / height cause I noticed some logos are much bigger / smaller than others

2024-06-23 11:41 UTC, derekxu04 commented on frontend/src/components/Sponsors/sponsorModal.tsx
> +          close
I think making this `Close` looks better

2024-06-23 11:41 UTC, derekxu04 commented on frontend/src/components/Sponsors/sponsorlinks.tsx
Can we rename this file `SponsorLinks.tsx` just to keep consistent

2024-06-23 11:41 UTC, derekxu04 commented on frontend/src/components/Sponsors/sponsorModal.tsx
Can we rename this `SponsorModal.tsx` for consistency

2024-06-23 11:41 UTC, derekxu04 commented on frontend/src/components/Sponsors/sponsorlinks.tsx
>            {diamondLinks.map((item, index) => {
Would be good for the logo to maybe expand slightly and for the cursor to become a pointer on hover to indicate it is clickable (applies to all logos)

2024-06-23 15:48 UTC, QuadAces commented on frontend/src/components/Sponsors/sponsorModal.tsx
> +export default function SponsorModal(props: { sponsorInfo: sponsorInfo | null; setFalse: any }) {
yes sorry I don't know how to deal with TS to be honest, and I searched it up and always got some error unless I //@ts-ignored
I'll look into it.

2024-06-26 16:06 UTC, QuadAces commented on frontend/src/components/Sponsors/sponsorlinks.tsx
>            {diamondLinks.map((item, index) => {
Yep for sure. I tried making everything responsive. I tested myself and found that when the logos are hovered mouse defaults to pointer anyway, could you show me what you mean?

2024-06-26 16:36 UTC, QuadAces commented
Okay great, done pretty much everything. for data ts, I just propse that we have an object with 3 key values just to at least connect the data somehow e.g. {diamond sponsors: [], gold sponsors: []}
I obviously dont want to make things more complex than they should be, just think they should be grouped together. I've added everything else :P

2024-06-27 07:19 UTC, derekxu04 approved these changes

2024-06-27 07:20 UTC, derekxu04 commented
> Okay great, done pretty much everything. for data ts, I just propse that we have an object with 3 key values just to at least connect the data somehow e.g. {diamond sponsors: [], gold sponsors: []}

Yep that makes sense I'll do this in another ticket

2024-06-27 07:21 UTC, merged